### ISSUE TITLE
request to http://172.17.0.1:3012/chatgpt/conversation failed, reason: socket hang up

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [linweiyuan/go-chatgpt-api#163]
使用的docker-compose文件配置

version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web
    restart: unless-stopped
    ports:
      - 3002:3002
    environment:
      OPENAI_ACCESS_TOKEN: "TOKEN"
      TIMEOUT_MS: 60000
      API_REVERSE_PROXY: "http://172.17.0.1:3012/chatgpt/conversation"
    depends_on: 
      - go-chatgpt-api

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 3012:3012
    environment:
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped
  
使用的是美国VPS，curl可以通openai，所以在go-chatgpt-api中没有设置PROXY以及WARP，镜像也是最新拉取的，但访问chatgpt-web，页面能打开，开始conversation后提示request to http://172.17.0.1:3012/chatgpt/conversation failed, reason: socket hang up。端口监控也检查过，都是LISTEN状态。

**Comment by GitHubChrisChen8035** [comment]
补充一下chatgpt-web项目的log

FetchError: request to http://172.17.0.1:3012/chatgpt/conversation failed, reason: socket hang up
    at ClientRequest.<anonymous> (file:///app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:525:35)
    at Socket.socketOnEnd (node:_http_client:526:9)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}

**Comment by linweiyuan** [comment]
如果是同一个 compose 文件，建议用服务名代替 IP（不是错误只是建议）

错误在于端口 3012:3012，改为 3012:8080 即可

**Comment by GitHubChrisChen8035** [comment]
> 如果是同一个 compose 文件，建议用服务名代替 IP（不是错误只是建议）
> 
> 错误在于端口 3012:3012，改为 3012:8080 即可

修改为8080，已经正常，这个port映射，是指将宿主机的3012端口和容器自身的8080端口进行绑定，对吧？
然后http://172.17.0.1:3012/chatgpt/conversation，这里的172.17.0.1是容器间通信的网关，加上3012这个已经映射过的端口，实际指向的是容器IP:8080，也就是go-chatgpt-api这个容器，我这样理解是否正确？

最后，服务器名是什么？localhost?

**Comment by GitHubChrisChen8035** [comment]
> 如果是同一个 compose 文件，建议用服务名代替 IP（不是错误只是建议）
> 
> 错误在于端口 3012:3012，改为 3012:8080 即可

修改成服务名称后，会提示connect ECONNREFUSED 172.18.0.2:3012（这个IP很奇怪）
FetchError: request to http://go-chatgpt-api:3012/chatgpt/conversation failed, reason: connect ECONNREFUSED 172.18.0.2:3012
    at ClientRequest.<anonymous> (file:///app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:525:35)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  erroredSysCall: 'connect'
}

**Comment by linweiyuan** [comment]
理解正确

服务名的话要 8080，并且可以注释掉 ports 配置，不暴露端口出去，不占用主机端口

**Comment by GitHubChrisChen8035** [comment]
> 理解正确
> 
> 服务名的话要 8080，并且可以注释掉 ports 配置，不暴露端口出去，不占用主机端口

感谢耐心解答，最后一个小问题，您的镜像更新频率高吗？是否要使用您推荐的自动更新镜像的配置？
