### ISSUE TITLE
本地部署报了一些错误

### ISSUE THREAD

**Issue by citcon-aoyansheng** [linweiyuan/go-chatgpt-api#62]
本地环境：
机器Mac pro m1

.yml配置

   go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
      CHATGPT_PROXY_SERVER: http://chatgpt-proxy-server:9515
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
    ports:
      - 9515:9515

chatgpt-proxy-server

容器运行log 

`
ERRO[0002] Please make sure chatgpt proxy service is running 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7af98b]

goroutine 7 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
	/app/webdriver/refresh.go:12 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
	/app/webdriver/refresh.go:11 +0x6a
ERRO[0004] Please make sure chatgpt proxy service is running 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7af98b]

goroutine 7 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
	/app/webdriver/refresh.go:12 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
	/app/webdriver/refresh.go:11 +0x6a
ERRO[0004] Please make sure chatgpt proxy service is running 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7af98b]

goroutine 53 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
	/app/webdriver/refresh.go:12 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
	/app/webdriver/refresh.go:11 +0x6a
ERRO[0004] Please make sure chatgpt proxy service is running 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7af98b]

goroutine 37 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
	/app/webdriver/refresh.go:12 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
	/app/webdriver/refresh.go:11 +0x6a
`

chatgpt-proxy-server

`
[1681997982.287][INFO]: [ca4ba8d87a94242e50b499bab830a4a8] COMMAND InitSession {
   "capabilities": {
      "alwaysMatch": {
      }
   },
   "desiredCapabilities": {
      "chromeOptions": {
         "args": [ "--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage", "--disable-blink-features=AutomationControlled", "--headless=new" ],
         "excludeSwitches": [ "enable-automation" ],
         "w3c": false
      }
   }
}
[1681997982.288][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1681997982.288][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1681997982.288][INFO]: Launching chrome: /opt/google/chrome/google-chrome --allow-pre-commit-input --disable-background-networking --disable-blink-features=AutomationControlled --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-blink-features=ShadowDOMV0 --enable-logging --headless=new --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.cZmWsd data:,
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[355:355:0420/133943.986547:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[320:320:0420/133944.041314:ERROR:browser_dm_token_storage_linux.cc(100)] Error: /etc/machine-id contains 0 characters (32 were expected).
[320:364:0420/133944.115322:ERROR:file_path_watcher_inotify.cc(315)] inotify_init() failed: Function not implemented (38)
[320:367:0420/133944.135205:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[320:370:0420/133944.230708:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[320:370:0420/133944.231338:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[320:367:0420/133944.307150:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[320:367:0420/133944.307552:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
qemu: unknown option 'type=utility'
[320:367:0420/133944.660395:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[320:367:0420/133944.660937:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

DevTools listening on ws://127.0.0.1:46761/devtools/browser/6b7d9ae9-3db5-4c54-828c-09b7b308e3ea
[1681997985.274][DEBUG]: DevTools HTTP Request: http://localhost:46761/json/version
[320:320:0420/133945.778638:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[320:320:0420/133945.794970:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
qemu: unknown option 'type=utility'
[1681997985.901][DEBUG]: DevTools HTTP Response: {
   "Browser": "Chrome/112.0.5615.121",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
   "V8-Version": "11.2.214.14",
   "WebKit-Version": "537.36 (@39cc4e45904ae9f1741c4fbaa866e629c96f2268)",
   "webSocketDebuggerUrl": "ws://localhost:46761/devtools/browser/6b7d9ae9-3db5-4c54-828c-09b7b308e3ea"
}

[1681997985.902][DEBUG]: DevTools HTTP Request: http://localhost:46761/json/list
[320:320:0420/133945.952624:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[320:391:0420/133945.952866:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[320:391:0420/133945.953306:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[320:391:0420/133945.954517:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[320:391:0420/133945.955282:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[320:391:0420/133945.956082:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[320:320:0420/133945.965872:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
qemu: unknown option 'type=utility'
[1681997986.011][DEBUG]: DevTools HTTP Response: [  ]

[320:320:0420/133946.015791:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[320:320:0420/133946.027354:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
qemu: unknown option 'type=utility'
[1681997986.061][DEBUG]: DevTools HTTP Request: http://localhost:46761/json/list
[320:320:0420/133946.059357:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[320:320:0420/133946.073132:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
[320:320:0420/133946.084016:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[1681997986.097][DEBUG]: DevTools HTTP Response: [  ]

qemu: unknown option 'type=utility'
[320:320:0420/133946.092081:ERROR:gpu_process_host.cc(936)] GPU process launch failed: error_code=1002
[320:320:0420/133946.092250:FATAL:gpu_data_manager_impl_private.cc(440)] GPU process isn't usable. Goodbye.
[0420/133946.095312:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
qemu: uncaught target signal 6 (Aborted) - core dumped
[1681997986.148][DEBUG]: DevTools HTTP Request: http://localhost:46761/json/list
[1681997986.152][DEBUG]: DevTools HTTP Request failed
[1681997986.851][INFO]: [ca4ba8d87a94242e50b499bab830a4a8] RESPONSE InitSession ERROR unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[1681997986.851][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1681997986.851][DEBUG]: Log type 'browser' lost 0 entries on destruction

`

**Comment by linweiyuan** [comment]
这个错误看上去有点底层，类似 CPU 架构不兼容啥的，我也没用过苹果，手头也没设备测试，太底层涉及硬件我也不懂

这个目前看上去貌似没能力修复

**Comment by linweiyuan** [comment]
https://github.com/pengzhile/pandora/blob/master/src/pandora/openai/api.py#L112

无法分析
